name: macOS

on:
  push:
    branches:
    - master

env:
  LIBGIT2_VERSION: 1.1.0
  MACOSX_DEPLOYMENT_TARGET: "10.9"

jobs:
  build:
    name: py-${{ matrix.py.ver }}
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        libgit2: ['maint/v1.1']
        py:
          - ver: '3.6'
            release: '3.6.8'  # last Python.org binary release
          - ver: '3.7'
            release: '3.7.9'  # last Python.org binary release
          - ver: '3.8'
            release: '3.8.7'
          - ver: '3.9'
            release: '3.9.1'
    steps:
      - name: Checkout pygit2
        uses: actions/checkout@v2

      - name: Setup python
        run: |
          PKG="python-${{ matrix.py.release }}-macosx10.9.pkg"
          URL="https://www.python.org/ftp/python/${{ matrix.py.release }}/$PKG"
          wget --no-verbose -N "$URL"
          sudo installer -pkg $PKG -target /
          export PATH=/Library/Frameworks/Python.framework/Versions/${{ matrix.py.ver }}/bin:$PATH
          echo "/Library/Frameworks/Python.framework/Versions/${{ matrix.py.ver }}/bin" >> $GITHUB_PATH
          which python3
          python3 -VV
          test "$(python3 -V)" = "Python ${{ matrix.py.release }}"

      - name: Build
        run: |
          /bin/sh build.sh wheel
          pip3 install delocate
          delocate-listdeps dist/pygit2-*macosx*.whl
          delocate-wheel -v -w dist/fixed-wheels/ dist/pygit2-*macosx*.whl
          WHEEL=$(basename dist/fixed-wheels/*.whl)
          echo "::set-output name=wheel::$WHEEL"
          delocate-listdeps dist/fixed-wheels/$WHEEL

      - name: Tests
        run: |
          pip3 install pytest
          pip3 install dist/fixed-wheels/pygit2-*.whl
          pytest

      - name: Save wheel
        uses: actions/upload-artifact@v1
        with:
          name: "macOS-wheel-py_${{ matrix.py.ver }}-libgit2_${{ env.LIBGIT2_VERSION }}"
          path: dist/fixed-wheels/
